name: bite_sized
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  timeago: ^3.0.2
  email_validator: ^2.1.17
  localstorage: ^4.0.0+1
  http: ^0.13.5
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  get_it: ^7.2.0
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  file_picker: ^5.2.3
  # firebase_core: ^1.23.0
  # file_picker: ^4.0.3
  # firebase_storage: ^10.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^0.22.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

flutter:
  assets:
    - assets/images/
  uses-material-design: true

